### ISSUE TITLE
great work on pub/sub. any benchmark?

### ISSUE THREAD

**Issue by hiqsociety** [tidwall/redcon#36]
great work on pub/sub. any benchmark compared with redis? it's really good.

**Comment by tidwall** [comment]
Thanks. I'm not aware of any public tools for benchmarking Redis pub/sub, and I didn't make one myself. Do you know of one in the wild? I would be interested too.

That being said, my implementation *should* perform very well because each subscriber runs in their own thread and each channel that they subscribe to is stored as an entry in a b-tree. Also publishers won't block the rest of the Redcon system while sending messages, and won't block other publishers too. So it should scale very well.

**Comment by gitmko0** [comment]
i think they use this against redis
https://docs.nats.io/nats-tools/natsbench
